### ISSUE TITLE
Workflow Image

### ISSUE THREAD

**Issue by juliangaal** [p-ranav/hypergrep#43]
Quick question: how did you create [this workflow](https://raw.githubusercontent.com/p-ranav/hypergrep/master/doc/images/workflow.png)

Amazing work, thank you.

**Comment by p-ranav** [comment]
Thanks! I made the image in Microsoft PowerPoint. I set the size of the slide to largest possible (50x50inch, I think?) and stuck to very basic shapes.

**Comment by juliangaal** [comment]
Ah, ok! Looks like it was creates with a dedicated tool, that's why I was wondering. Thanks.
